#!/usr/bin/env python3

import sys
import footballscoreboard

if __name__ == "__main__":
    app = footballscoreboard.App()
    try:
        app.load_plugins(sys.argv[1:])
        app.run()
    except (KeyboardInterrupt, SystemExit):
        app.exit()
